# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tandemn.chunkmanager.v1 import chunk_manager_pb2 as tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tandemn/chunkmanager/v1/chunk_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlannerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/tandemn.chunkmanager.v1.PlannerService/CreateJob',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CreateJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/tandemn.chunkmanager.v1.PlannerService/GetJob',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.GetJobRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.RegisterChunks = channel.unary_unary(
                '/tandemn.chunkmanager.v1.PlannerService/RegisterChunks',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RegisterChunksRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RegisterChunksResponse.FromString,
                _registered_method=True)
        self.FinalizeJobRegistration = channel.unary_unary(
                '/tandemn.chunkmanager.v1.PlannerService/FinalizeJobRegistration',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FinalizeJobRegistrationRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FinalizeJobRegistrationResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/tandemn.chunkmanager.v1.PlannerService/CancelJob',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.AddChainAssociation = channel.unary_unary(
                '/tandemn.chunkmanager.v1.PlannerService/AddChainAssociation',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.AddChainAssociationRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.AddChainAssociationResponse.FromString,
                _registered_method=True)
        self.DrainChainAssociation = channel.unary_unary(
                '/tandemn.chunkmanager.v1.PlannerService/DrainChainAssociation',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.DrainChainAssociationRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.DrainChainAssociationResponse.FromString,
                _registered_method=True)


class PlannerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeJobRegistration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddChainAssociation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainChainAssociation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CreateJobRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CreateJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.GetJobRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.GetJobResponse.SerializeToString,
            ),
            'RegisterChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterChunks,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RegisterChunksRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RegisterChunksResponse.SerializeToString,
            ),
            'FinalizeJobRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeJobRegistration,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FinalizeJobRegistrationRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FinalizeJobRegistrationResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CancelJobRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CancelJobResponse.SerializeToString,
            ),
            'AddChainAssociation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChainAssociation,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.AddChainAssociationRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.AddChainAssociationResponse.SerializeToString,
            ),
            'DrainChainAssociation': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainChainAssociation,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.DrainChainAssociationRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.DrainChainAssociationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tandemn.chunkmanager.v1.PlannerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tandemn.chunkmanager.v1.PlannerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlannerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.PlannerService/CreateJob',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CreateJobRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.PlannerService/GetJob',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.GetJobRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.PlannerService/RegisterChunks',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RegisterChunksRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RegisterChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeJobRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.PlannerService/FinalizeJobRegistration',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FinalizeJobRegistrationRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FinalizeJobRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.PlannerService/CancelJob',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CancelJobRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddChainAssociation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.PlannerService/AddChainAssociation',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.AddChainAssociationRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.AddChainAssociationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainChainAssociation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.PlannerService/DrainChainAssociation',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.DrainChainAssociationRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.DrainChainAssociationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClaimChunks = channel.unary_unary(
                '/tandemn.chunkmanager.v1.WorkerService/ClaimChunks',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.ClaimChunksRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.ClaimChunksResponse.FromString,
                _registered_method=True)
        self.RenewLeases = channel.unary_unary(
                '/tandemn.chunkmanager.v1.WorkerService/RenewLeases',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RenewLeasesRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RenewLeasesResponse.FromString,
                _registered_method=True)
        self.CompleteChunk = channel.unary_unary(
                '/tandemn.chunkmanager.v1.WorkerService/CompleteChunk',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CompleteChunkRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CompleteChunkResponse.FromString,
                _registered_method=True)
        self.FailChunk = channel.unary_unary(
                '/tandemn.chunkmanager.v1.WorkerService/FailChunk',
                request_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FailChunkRequest.SerializeToString,
                response_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FailChunkResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ClaimChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLeases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClaimChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimChunks,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.ClaimChunksRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.ClaimChunksResponse.SerializeToString,
            ),
            'RenewLeases': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLeases,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RenewLeasesRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RenewLeasesResponse.SerializeToString,
            ),
            'CompleteChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteChunk,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CompleteChunkRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CompleteChunkResponse.SerializeToString,
            ),
            'FailChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.FailChunk,
                    request_deserializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FailChunkRequest.FromString,
                    response_serializer=tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FailChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tandemn.chunkmanager.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tandemn.chunkmanager.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClaimChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.WorkerService/ClaimChunks',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.ClaimChunksRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.ClaimChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLeases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.WorkerService/RenewLeases',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RenewLeasesRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.RenewLeasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.WorkerService/CompleteChunk',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CompleteChunkRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.CompleteChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tandemn.chunkmanager.v1.WorkerService/FailChunk',
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FailChunkRequest.SerializeToString,
            tandemn_dot_chunkmanager_dot_v1_dot_chunk__manager__pb2.FailChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
