---
apiVersion: batch/v1
kind: Job
metadata:
  name: batched-worker-test
  namespace: tandemn-system

spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        tandemn.com/job-type: batched-inference
        tandemn.com/job-id: "00000000000000000000000001"
        tandemn.com/rank-id: "00000000000000000000000001"
        tandemn.com/chain-id: "1"
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 90

      nodeSelector:
        cloud.google.com/gke-nodepool: g2-standard-48

      containers:
        - name: tandemn-worker
          image: "us-docker.pkg.dev/tandemn/tandemn-worker/tandemn-worker:v0.0.1-vllm0.28.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: TD_VLLM_MODEL
              value: "microsoft/phi-4"
            - name: TD_VLLM_HOST
              value: "0.0.0.0"
            - name: TD_VLLM_EXTRA_ARGS
              value: "--pipeline-parallel-size=2 --tensor-parallel-size=2"

            - name: TD_CHUNK_MANAGER_ADDRESS
              value: "${TD_CHUNK_MANAGER_ADDRESS}"
            - name: TD_JOB_ID
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['tandemn.com/job-id']"
            - name: TD_RANK_ID
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['tandemn.com/rank-id']"
            - name: TD_CHAIN_ID
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['tandemn.com/chain-id']"

            - name: AWS_DEFAULT_REGION
              value: "${AWS_DEFAULT_REGION}"

          envFrom:
            - secretRef:
                name: tandemn-worker-secrets
                optional: false

          ports:
            - name: metrics
              containerPort: 9000
            - name: vllm
              containerPort: 8000

          resources:
            requests:
              cpu: "1"
              memory: 16Gi
              nvidia.com/gpu: "4"
            limits:
              nvidia.com/gpu: "4"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 96Gi
